ARG DEBIAN_VERSION=bookworm
ARG NODE_VERSION=20
FROM node:${NODE_VERSION}-${DEBIAN_VERSION} AS Build

WORKDIR /opt/weacast

RUN git clone https://github.com/weacast/weacast-app.git -b master --single-branch && cd weacast-app && yarn install && cd ..

FROM weacast/weacast-api:dev-node${NODE_VERSION}-${DEBIAN_VERSION}

COPY --from=Build --chown=node:node /opt/weacast/weacast-app/dist /opt/weacast/weacast/packages/api/dist
