FROM  node:16-bookworm AS Build

WORKDIR /opt/weacast

RUN git clone https://github.com/weacast/weacast-app.git -b master --single-branch && cd weacast-app && yarn install && cd ..

FROM  weacast/weacast-api:dev

COPY --from=Build --chown=node:node /opt/weacast/weacast-app/dist /opt/weacast/weacast/packages/api/dist
