name: CI
on: [ push, workflow_dispatch ]

jobs:
  build_app:
    name: Build app
    if: ${{ !contains(github.event.head_commit.message, 'skip app') }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node: [ 20 ]
        debian: [ 'bookworm' ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Init runner
        run: bash ./scripts/init_runner.sh ${{ github.job }}
      - name: Setup workspace
        env:
          KALISIO_GITHUB_URL: ${{ secrets.KALISIO_GITHUB_URL }}
        run: bash ./scripts/setup_workspace.sh
      - name: Build app
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: bash ./scripts/build_app.sh -p -r ${{ github.job }} -n ${{ matrix.node }} -d ${{ matrix.debian }}
